version: '3.8'
services: #app components like UI,logs,DB...
  siva-ui-service:
    image: siva-webui:version$BUILD_NUMBER
    build: 
      context: . #loction of dockerfile
      dockerfile: Dockerfile
    container_name: siva-web-c2 #name of container
    ports:
      - 4747:80 # you can use 1024-5000 range