apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sivalb1
  name: sivalb1 # change name of service
  namespace: siva-space # adding namespace 
spec:
  ports:
  - name: 4477-80
    port: 4477
    protocol: TCP
    targetPort: 80
  selector: # you have match label with pod template
   app: siva-dep1 # update label of pod template section
  type: NodePort
status:
  loadBalancer: {}
